/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopcopyRouteImport } from './routes/shop copy'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as WholesaleEnquiryRouteImport } from './routes/wholesale.enquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopcopyRoute = ShopcopyRouteImport.update({
  id: '/shop copy',
  path: '/shop copy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/wholesale/',
  path: '/wholesale/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleEnquiryRoute = WholesaleEnquiryRouteImport.update({
  id: '/wholesale/enquiry',
  path: '/wholesale/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/shop': typeof ShopRoute
  '/shop copy': typeof ShopcopyRoute
  '/story': typeof StoryRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/wholesale/enquiry': typeof WholesaleEnquiryRoute
  '/wholesale/': typeof WholesaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/shop': typeof ShopRoute
  '/shop copy': typeof ShopcopyRoute
  '/story': typeof StoryRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/wholesale/enquiry': typeof WholesaleEnquiryRoute
  '/wholesale': typeof WholesaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/shop': typeof ShopRoute
  '/shop copy': typeof ShopcopyRoute
  '/story': typeof StoryRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/wholesale/enquiry': typeof WholesaleEnquiryRoute
  '/wholesale/': typeof WholesaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contact'
    | '/locations'
    | '/shop'
    | '/shop copy'
    | '/story'
    | '/wishlist'
    | '/product/$slug'
    | '/wholesale/enquiry'
    | '/wholesale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/locations'
    | '/shop'
    | '/shop copy'
    | '/story'
    | '/wishlist'
    | '/product/$slug'
    | '/wholesale/enquiry'
    | '/wholesale'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contact'
    | '/locations'
    | '/shop'
    | '/shop copy'
    | '/story'
    | '/wishlist'
    | '/product/$slug'
    | '/wholesale/enquiry'
    | '/wholesale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  LocationsRoute: typeof LocationsRoute
  ShopRoute: typeof ShopRoute
  ShopcopyRoute: typeof ShopcopyRoute
  StoryRoute: typeof StoryRoute
  WishlistRoute: typeof WishlistRoute
  ProductSlugRoute: typeof ProductSlugRoute
  WholesaleEnquiryRoute: typeof WholesaleEnquiryRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop copy': {
      id: '/shop copy'
      path: '/shop copy'
      fullPath: '/shop copy'
      preLoaderRoute: typeof ShopcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/wholesale'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/enquiry': {
      id: '/wholesale/enquiry'
      path: '/wholesale/enquiry'
      fullPath: '/wholesale/enquiry'
      preLoaderRoute: typeof WholesaleEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  LocationsRoute: LocationsRoute,
  ShopRoute: ShopRoute,
  ShopcopyRoute: ShopcopyRoute,
  StoryRoute: StoryRoute,
  WishlistRoute: WishlistRoute,
  ProductSlugRoute: ProductSlugRoute,
  WholesaleEnquiryRoute: WholesaleEnquiryRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
